### ISSUE TITLE
при попытке получить имя элемента возвращается только его тип

### ISSUE THREAD

**Issue by koleeees** [yandex-qatools/htmlelements-dotnet#2]
если при объявлении элемента указать его имя через атрибут Name, то при получении значения имени элемента возвращается его тип. 
пример:

объявляем элемент
        [Yandex.HtmlElements.Attributes.Name("ololo")]
        [FindsBy(How = How.XPath, Using = "//*[@id=\"fellow-to\"]/footer/div/div[2]/ul/li[3]/a/l10n")]
        protected Link lnkTerms = null;

записываем в лог запись с получением имени элемента 
        public TermsPage TermsClick()
        {
            TestLog.WriteLine("Нажимаем на элемент "+lnkTerms.Name);
            lnkTerms.Click();
            return new TermsPage(driver);
        } 

В результате в лог пишется только "Нажимаем на элемент Link"

**Comment by HardNorth** [comment]
Привет!
Pull request с фиксом заслал, теперь дело за Артёмом.

**Comment by HardNorth** [comment]
Поторопился, немножко переделал фикс.

**Comment by HardNorth** [comment]
Please close the issue
